# Generated by Django 4.2.17 on 2026-06-08 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('general', 'General'), ('application', 'Application'), ('interview', 'Interview'), ('job_alert', 'Job Alert'), ('message', 'Message')], default='general', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='ref_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the related object (application, interview, etc.)', null=True),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(help_text='Firebase Cloud Messaging registration token from the device.')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'unique_together': {('user', 'fcm_token')},
            },
        ),
    ]
