# Generated by Django 4.2.17 on 2026-05-11 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='AI-generated professional summary'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='certifications_json',
            field=models.JSONField(blank=True, default=list, help_text='["AWS Certified", ...]'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='education_json',
            field=models.JSONField(blank=True, default=list, help_text='[{"institution":"","degree":"","field":"","year":""}]'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='is_searchable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_completeness',
            field=models.IntegerField(default=0, help_text='0-100 score based on filled sections'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_experience_json',
            field=models.JSONField(blank=True, default=list, help_text='[{"company":"","role":"","duration":"","description":""}]'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='company_website',
            field=models.URLField(blank=True),
        ),
    ]
