# Generated by Django 4.2.29 on 2026-03-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_match_score', models.FloatField(default=0.0)),
                ('ats_status', models.CharField(default='new', max_length=50)),
                ('skill_gap_analysis', models.JSONField(blank=True, default=list)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('required_skills_json', models.JSONField(blank=True, default=list)),
                ('min_experience', models.IntegerField(default=0)),
                ('job_type', models.CharField(default='onsite', max_length=50)),
                ('status', models.CharField(default='active', max_length=50)),
                ('vector_profile', models.JSONField(blank=True, default=list)),
                ('search_keywords_index', models.TextField(blank=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
