# Generated by Django 4.2.29 on 2026-03-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_meeting_link', models.URLField(blank=True)),
                ('scheduled_datetime', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=50)),
            ],
        ),
    ]
