# Generated by Django 4.2.17 on 2026-06-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_delete_scheduledinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='zoom_host_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='interview',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=50),
        ),
    ]
