# Generated by Django 4.2.17 on 2026-06-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_alter_application_options_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0, help_text='Overall AI match score (0-100)')),
                ('skill_match_pct', models.FloatField(default=0.0, help_text='Percentage of required skills matched')),
                ('experience_match', models.BooleanField(default=False, help_text='Whether candidate meets min experience')),
                ('matched_skills', models.JSONField(default=list, help_text='List of skills candidate has that job requires')),
                ('missing_skills', models.JSONField(default=list, help_text='List of required skills the candidate lacks')),
                ('recommendation', models.TextField(blank=True, help_text='Gemini-generated career recommendation')),
                ('generated_at', models.DateTimeField(auto_now=True, help_text='When this report was last generated/updated')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_report', to='jobs.application')),
            ],
            options={
                'verbose_name': 'AI Match Report',
                'verbose_name_plural': 'AI Match Reports',
            },
        ),
    ]
