# Generated by Django 4.2.29 on 2026-03-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted by parser')),
                ('skills_extracted', models.TextField(blank=True, help_text='JSON or comma separated skills')),
                ('parsed_experience', models.IntegerField(default=0)),
                ('parsed_education', models.JSONField(blank=True, default=list)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
    ]
